from .api.specification import (
    CONST_FIELD_KEYWORD,
    CONST_FIELD_MATCH,
    CONST_FIELD_MATCHEND,
    CONST_FIELD_TARGET,
    CONST_FIELD_TARGET_0,
    CONST_FIELD_TARGET_1,
    CONST_FIELD_TARGET_2,
    CONST_FIELD_TARGET_3,
    CONST_FIELD_TARGET_4,
    CONST_FIELD_TARGET_5,
    CONST_FIELD_TARGET_6,
    CONST_FIELD_TARGET_7,
    CONST_FIELD_TARGET_8,
    CONST_FIELD_TARGET_9
)


FIELD_KEYWORD: int = CONST_FIELD_KEYWORD
FIELD_MATCH: int = CONST_FIELD_MATCH
FIELD_MATCHEND: int = CONST_FIELD_MATCHEND
FIELD_TARGET: int = CONST_FIELD_TARGET
FIELD_TARGET_0: int = CONST_FIELD_TARGET_0
FIELD_TARGET_1: int = CONST_FIELD_TARGET_1
FIELD_TARGET_2: int = CONST_FIELD_TARGET_2
FIELD_TARGET_3: int = CONST_FIELD_TARGET_3
FIELD_TARGET_4: int = CONST_FIELD_TARGET_4
FIELD_TARGET_5: int = CONST_FIELD_TARGET_5
FIELD_TARGET_6: int = CONST_FIELD_TARGET_6
FIELD_TARGET_7: int = CONST_FIELD_TARGET_7
FIELD_TARGET_8: int = CONST_FIELD_TARGET_8
FIELD_TARGET_9: int = CONST_FIELD_TARGET_9
